servers:
  irc.freenode.net:
    channels:
      '#cubecraft':
        url: https://www.cubecraftgames.net/forums/-/index.rss
        type: rss
name: KellyBot
real-name: KellyBot
login: KellyBot
cap-enabled: true
auto-nick-change: true
auto-split-message: false
max-line-length: null
message-delay: null
password: null
startup-delay: 60
check-rss-delay: 10
# You can use the following in the message format:
# %title : The title of the feed entry
# %description : The description/content of the feed entry
# %link : The link to the feed entry
# %author : The author of the feed entry
message-format: '%title >> %link'